apiVersion: v1
kind: Pod
metadata:
  name: hackerwhale
  labels:
    app: hackerwhale
spec:
  containers:
    - name: hackerwhale
      image: 0xtiago/hackerwhale:latest
      command: ["/bin/zsh", "-c", "while true; do sleep 30; done;"]
      tty: true
      stdin: true
